"""
Evidence Pack Export — generates a ZIP file containing all legal evidence
for a signing event.

Contents:
  - Signed PDF
  - Audit events JSON
  - Certificate chain (PEM)
  - OCSP response (DER)
  - README.txt
"""

import base64
import io
import json
import zipfile

import frappe


@frappe.whitelist()
def export_evidence_pack(signing_request):
	"""Generate and download a legal evidence pack ZIP for a signing request.

	Args:
		signing_request: name of the DSC Signing Request

	Returns:
		Sends the ZIP file as a download response
	"""
	req = frappe.get_doc("DSC Signing Request", signing_request)

	if req.status != "Signed":
		frappe.throw("Evidence pack can only be exported for signed requests.")

	# Build the ZIP in memory
	zip_buffer = io.BytesIO()

	with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
		# 1. Signed PDF
		if req.signed_file:
			file_doc = frappe.get_doc("File", req.signed_file)
			file_content = file_doc.get_content()
			zf.writestr(f"signed_{req.source_name}.pdf", file_content)

		# 2. Audit events JSON
		audit_events = frappe.get_all(
			"DSC Audit Event",
			filters={"request": signing_request},
			fields=[
				"name", "event_type", "occurred_at", "actor_user",
				"client_ip", "user_agent", "details_json", "event_hash",
			],
			order_by="occurred_at asc",
		)

		# Convert datetime to string for JSON serialization
		for event in audit_events:
			event["occurred_at"] = str(event["occurred_at"])

		audit_json = json.dumps(
			{
				"signing_request": signing_request,
				"source_doctype": req.source_doctype,
				"source_name": req.source_name,
				"status": req.status,
				"signed_on": str(req.signed_on),
				"signer_user": req.actual_signer_user,
				"certificate_fingerprint": req.certificate_fingerprint_presented,
				"hash_algorithm": req.hash_algorithm,
				"events": audit_events,
			},
			indent=2,
			default=str,
		)
		zf.writestr("audit_trail.json", audit_json)

		# 3. Certificate (if available from profile)
		profile = frappe.get_doc("DSC Profile", req.profile)
		if profile.certificate_pem_public:
			zf.writestr("signer_certificate.pem", profile.certificate_pem_public)

		# 4. OCSP response (if available)
		if req.ocsp_response_b64:
			try:
				# Strip the truncation marker if present
				ocsp_b64 = req.ocsp_response_b64.rstrip(".")
				ocsp_der = base64.b64decode(ocsp_b64)
				zf.writestr("ocsp_response.der", ocsp_der)
			except Exception:
				pass  # OCSP data may be truncated in storage

		# 5. README
		readme = build_readme(req, profile, audit_events)
		zf.writestr("README.txt", readme)

	# Send as download
	zip_buffer.seek(0)
	zip_bytes = zip_buffer.read()

	frappe.local.response.filename = f"evidence_pack_{signing_request}.zip"
	frappe.local.response.filecontent = zip_bytes
	frappe.local.response.type = "download"


def build_readme(req, profile, audit_events):
	"""Build a human-readable README for the evidence pack."""
	return f"""DIGITAL SIGNATURE EVIDENCE PACK
================================

Signing Request:  {req.name}
Source Document:   {req.source_doctype} / {req.source_name}
Status:           {req.status}

SIGNER INFORMATION
------------------
Profile:          {profile.profile_name}
Signer Name:      {profile.certificate_common_name or profile.label}
Designation:      {profile.designation_for_stamp or profile.label or 'N/A'}
Certificate:      {profile.certificate_fingerprint or 'N/A'}
Issuer:           {profile.certificate_issuer or 'N/A'}
Valid From:        {profile.certificate_not_before or 'N/A'}
Valid Until:       {profile.certificate_not_after or 'N/A'}

SIGNING DETAILS
---------------
Signed By User:   {req.actual_signer_user}
Signed On:        {req.signed_on}
Hash Algorithm:   {req.hash_algorithm}
Duration:         {req.sign_duration_seconds or 'N/A'} seconds
Client IP:        {req.client_ip or 'N/A'}

CONTENTS OF THIS PACK
---------------------
1. signed_{req.source_name}.pdf  — The digitally signed PDF document
2. audit_trail.json             — Complete audit trail with {len(audit_events)} events
3. signer_certificate.pem       — Public certificate of the signer (PEM format)
4. ocsp_response.der            — OCSP response at time of signing (DER format)
5. README.txt                   — This file

VERIFICATION
------------
To verify the signed PDF:
1. Open the PDF in Adobe Acrobat Reader
2. Check the signature panel for validity
3. The signature should show as valid if the signer's CA root
   is in Adobe's Approved Trust List (AATL)

For Indian CAs (eMudhra, Sify, nCode), the root certificates
are included in Adobe's AATL by default.

LEGAL NOTICE
------------
This evidence pack is generated by the frappe_dsc digital signing
platform. The audit trail records are append-only and tamper-evident.
The signed PDF conforms to the PAdES B-B signature standard.

Generated on: {frappe.utils.now_datetime()}
"""
